trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployStage
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
            npm install -g @angular/cli
            npm install
            ng build 

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/automationdemo'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'

  - job: Deploy
    displayName: 'Deploy to VM'
    dependsOn: Build
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download artifact'
      inputs:
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'

    - powershell: |
        Expand-Archive -Path "$(System.ArtifactsDirectory)/$(Build.BuildId).zip" -DestinationPath "$(System.ArtifactsDirectory)/extracted"
      displayName: 'Extract artifact'

    - powershell: Get-ChildItem -Path "$(System.ArtifactsDirectory)/extracted" -Recurse
      displayName: 'List extracted files'

    - task: CopyFiles@2
      displayName: 'Copy files to staging directory'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/extracted'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: CopyFilesOverSSH@0
      displayName: 'Copy files to remote VM'
      inputs:
        sshEndpoint: 'automation'
        sourceFolder: '$(System.ArtifactsDirectory)/extracted'
        contents: '**/*'
        targetFolder: '/home/azureuser/'

    - task: SSH@0
      displayName: 'Move files and restart Apache'
      inputs:
        sshEndpoint: 'automation'
        runOptions: 'inline'
        inline: |
          sudo mv /home/azureuser/* /var/www/html/
          sudo systemctl restart apache2
